# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  
jobs:
  publish-to-tableau-server:
    runs-on: windows-latest
    steps:
      - name: Get changed files
        uses: actions/checkout@v2.1.0
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
            format: 'csv'
            token: ${{ secrets.ACTIONS_KEY}}
            
      - name: Install Tabcmd
        run: pip install tabcmd

      - name: Tableau Login
        run: tabcmd login --no-certcheck -s "${{ secrets.TABLEAU_HOST }}" -t "${{ secrets.TABLEAU_SITE }}"  --token-name "${{ secrets.TABLEAU_TOKENNAME }}" --token-value "${{ secrets.TABLEAU_TOKENVALUE }}"
      
      - name: Publish Workbooks to Tableau Server
        run: tabcmd publish "TestBook.twbx" -n "My Tableau Workbook" --project "Github Actions Testing" --overwrite
